import {
    Shield,
    Database,
    Code,
    Cloud,
    Briefcase,
    Layout,
    Smartphone,
    Server,
    Brain,
    Wifi
} from 'lucide-react';

export const activityList=[
    { id: 1, name: 'Adriana', action: 'posted cloud system security', time: '1 Hour Ago' },
    { id: 2, name: 'Gracie', action: 'liked your post', time: '1 Hour Ago' },
    { id: 3, name: 'Peter', action: 'commented on your post', time: '2 Hours Ago' },
    { id: 4, name: 'Sophia', action: 'shared your post', time: '3 Hours Ago' },
    { id: 5, name: 'Michael', action: 'followed you', time: '4 Hours Ago' },
    { id: 6, name: 'Jessica', action: 'posted cloud system security', time: '5 Hours Ago' },
    { id: 7, name: 'Daniel', action: 'liked your post', time: '6 Hours Ago' },
    { id: 8, name: 'Emily', action: 'shared your post', time: '7 Hours Ago' },
    { id: 9, name: 'Joshua', action: 'commented on your post', time: '8 Hours Ago' },
    { id: 10, name: 'Sarah', action: 'posted cloud system security', time: '9 Hours Ago' },
    { id: 11, name: 'David', action: 'followed you', time: '10 Hours Ago' },
    { id: 12, name: 'Olivia', action: 'liked your post', time: '11 Hours Ago' },
    { id: 13, name: 'Ethan', action: 'shared your post', time: '12 Hours Ago' },
    { id: 14, name: 'Mia', action: 'commented on your post', time: '13 Hours Ago' },
    { id: 15, name: 'Alexander', action: 'posted cloud system security', time: '14 Hours Ago' },
    { id: 16, name: 'Isabella', action: 'followed you', time: '15 Hours Ago' },
    { id: 17, name: 'Matthew', action: 'liked your post', time: '16 Hours Ago' },
    { id: 18, name: 'Ella', action: 'shared your post', time: '17 Hours Ago' },
    { id: 19, name: 'Christopher', action: 'commented on your post', time: '18 Hours Ago' },
    { id: 20, name: 'Ava', action: 'posted cloud system security', time: '19 Hours Ago' },
    { id: 21, name: 'Andrew', action: 'followed you', time: '20 Hours Ago' },
    { id: 22, name: 'Sofia', action: 'liked your post', time: '21 Hours Ago' },
    { id: 23, name: 'Ryan', action: 'shared your post', time: '22 Hours Ago' },
    { id: 24, name: 'Zoe', action: 'commented on your post', time: '23 Hours Ago' }
];

export const wantedList = [
    { title: "Digital Marketing", reqCount: 12 },
    { title: "SOLID Principles", reqCount: 5 },
    { title: "Android Development", reqCount: 15 },
    { title: "Web Development", reqCount: 20 },
    { title: "Machine Learning Basics", reqCount: 8 },
    { title: "Data Structures and Algorithms", reqCount: 18 },
    { title: "React.js Essentials", reqCount: 10 },
    { title: "Node.js for Beginners", reqCount: 14 },
    { title: "UI/UX Design Fundamentals", reqCount: 6 },
    { title: "Cloud Computing", reqCount: 9 },
    { title: "Cybersecurity Awareness", reqCount: 11 },
    { title: "Big Data Analytics", reqCount: 7 },
    { title: "DevOps Practices", reqCount: 13 },
    { title: "Python Programming", reqCount: 16 },
    { title: "Artificial Intelligence", reqCount: 19 },
];
export const jobs = [
    {
        title: "Cyber Security",
        location: "Gurugram",
        icon: Shield,
        bgColor: "light",
        iconColor: "primary",
    },
    {
        title: "Data Science",
        location: "Andheri",
        icon: Database,
        bgColor: "info",
        iconColor: "white",
    },
    {
        title: "Web Development",
        location: "Bangalore",
        icon: Code,
        bgColor: "warning",
        iconColor: "dark",
    },
    {
        title: "Cloud Engineer",
        location: "Hyderabad",
        icon: Cloud,
        bgColor: "dark",
        iconColor: "light",
    },
    {
        title: "Product Manager",
        location: "Pune",
        icon: Briefcase,
        bgColor: "success",
        iconColor: "white",
    },
    {
        title: "UI/UX Designer",
        location: "Delhi",
        icon: Layout,
        bgColor: "primary",
        iconColor: "light",
    },
    {
        title: "Mobile App Developer",
        location: "Chennai",
        icon: Smartphone,
        bgColor: "secondary",
        iconColor: "white",
    },
    {
        title: "DevOps Engineer",
        location: "Noida",
        icon: Server,
        bgColor: "danger",
        iconColor: "white",
    },
    {
        title: "AI Engineer",
        location: "Mumbai",
        icon: Brain,
        bgColor: "info",
        iconColor: "dark",
    },
    {
        title: "Network Engineer",
        location: "Kolkata",
        icon: Wifi,
        bgColor: "primary",
        iconColor: "white",
    },
];